export const shopCategories = [
	{ value: "fashion", label: "Fashion" },
	{ value: "clothing", label: "Clothing" },
	{ value: "shoes", label: "Shoes" },
	{ value: "accessories", label: "Accessories" },
	{ value: "beauty", label: "Beauty & Personal Care" },
	{ value: "electronics", label: "Electronics" },
	{ value: "computers", label: "Computers & Accessories" },
	{ value: "home-garden", label: "Home & Garden" },
	{ value: "furniture", label: "Furniture" },
	{ value: "kitchen", label: "Kitchen" },
	{ value: "sports", label: "Sports & Outdoors" },
	{ value: "fitness", label: "Fitness" },
	{ value: "toys", label: "Toys & Games" },
	{ value: "books", label: "Books" },
	{ value: "music", label: "Music & Instruments" },
	{ value: "groceries", label: "Groceries" },
	{ value: "health", label: "Health & Wellness" },
	{ value: "baby", label: "Baby & Toddler" },
	{ value: "kids", label: "Kids" },
	{ value: "pet-supplies", label: "Pet Supplies" },
	{ value: "jewelry", label: "Jewelry" },
	{ value: "beauty-services", label: "Beauty Services" },
	{ value: "automotive", label: "Automotive & Parts" },
	{ value: "tools", label: "Tools & Home Improvement" },
	{ value: "office", label: "Office Supplies" },
	{ value: "garden", label: "Garden & Outdoor" },
	{ value: "handmade", label: "Handmade" },
	{ value: "art", label: "Art & Collectibles" },
	{ value: "antiques", label: "Antiques" },
	{ value: "services", label: "Local Services" },
	{ value: "games", label: "Video Games & Consoles" },
];
