import './global.css';
import {Poppins} from 'next/font/google'
import Providers from './provider';
export const metadata = {
  title: 'Ilan Shop Admin UI',
  description: 'Generated by create-nx-workspace',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800'],
  variable: '--font-poppins',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen text-white bg-slate-900 font-sans antialiased ${poppins.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
